### ISSUE TITLE
Show first error line number

### ISSUE THREAD

**Issue by alextrastero** [maximbaz/lightline-ale#12]
First of all thanks for this plugin :)

So far it works great, I was wondering if in addition to showing the error count I could also display the first error line number:
<img width="94" alt="screen shot 2018-06-22 at 13 43 30" src="https://user-images.githubusercontent.com/4152819/41774995-445c2a30-7622-11e8-8398-cc6185cd661a.png">

As in maybe `E: 1 L32`

**Comment by alextrastero** [comment]
Note: since I don't show them in the gutter

**Comment by maximbaz** [comment]
Hello 🙂 I see, but what would you do if you decide not to fix the first error? You will never know where is the second error... Have you considered just making ALE show the quickfix/loclist with the list of errors?

**Comment by alextrastero** [comment]
True, thanks for the tip!
```bashrc
# .vimrc
let g:ale_open_list = 1
```
