### ISSUE TITLE
Issues with setting the correct color for warning and error

### ISSUE THREAD

**Issue by Torbbang** [maximbaz/lightline-ale#14]
The plugin seems to have problems using the correct color for 'error' and 'warning'. It loads the stock colors and not the ones from my colorscheme. The error and warning colors seem to be correct elsewhere. Here's my [colorscheme](https://github.com/arcticicestudio/nord-vim/blob/develop/autoload/lightline/colorscheme/nord.vim) and [.vimrc](https://github.com/Torbbang/dots/blob/master/tools/.vim/.vimrc).

Edit: User error. I managed to miss that there was a duplicate "let g:lightline" in the .vimrc. Spent an hour troubleshooting before submitting, found the error 2 minutes after submitting this.

**Comment by maximbaz** [comment]
Great that you found a solution 😄 I'll close the issue since there's nothing to do.

**Comment by horseinthesky** [comment]
@maximbaz Could you please tell me how to check what color options I do have? And is it possible to set a custom color for icons?

**Comment by maximbaz** [comment]
If I remember correctly, the valid options are `left`, `warning` and `error` - they come from ALE itself. I don't think it's possible to configure icons colors, no...

**Comment by horseinthesky** [comment]
The thing is these `left`, `warning`, `error` (and I've found `raw` in the documentation of `lightline` change their color with changing the colorscheme of lightline and I would like to set ALE errors and warings blocks to keep their colors.

**Comment by maximbaz** [comment]
I see what you want 🤔 I don't know if it's possible, really depends on what `lightline` allows you to do for components. If you want to dig into this, my only idea is to try to define to a new type (e.g. `let g:lightline.component_type = { 'linter_errors': 'always_red' `), and then somehow set a colorscheme for this `always_red`... somehow.

Try to ask maybe on `lightline` issue tracker as well, how to set component_type to render to a specific color and not to colorscheme-dependent one.

**Comment by horseinthesky** [comment]
Ok. I've just started digging how `lightline` works and need to spend some time on it. Thank you.
