### ISSUE TITLE
README screenshot configuration

### ISSUE THREAD

**Issue by comfortablynick** [maximbaz/lightline-ale#15]
Hello,

I've been using this plugin and it's working great. One question I have: The warning/error sections seem to absorb the rightmost section formatting. The picture in README looks correct. On my config, I don't get the brighter/bolder colors on the right like I do on the left. 

I have the right side configured as per your instructions, as far as I can tell. Any ideas?

EDIT: I'm running VIM 8.1.401 on Ubuntu/WSL

![screenshot](https://cdn.pbrd.co/images/HOf0E7o.png "Lightline Screenshot")

**Comment by maximbaz** [comment]
I'm not exactly sure what you mean, the colors look consistent to my eye, but I'm probably missing the point here 🙂 Could you add some arrows pointing to the issue?

**Comment by maximbaz** [comment]
I see, hmmm I'm not sure. Have a look in my config, maybe you'll spot a difference?

https://github.com/maximbaz/dotfiles/blob/master/.config/nvim/init.vim

**Comment by comfortablynick** [comment]
Thank you! I did figure it out. You combined those segments which made it look correct. I appreciate it!

**Comment by basbebe** [comment]
The link doesn't work any more.
Is there a working configuration available that adds the ALE sections to the right side instead of replacing it?
Thanks

**Comment by maximbaz** [comment]
This was the state of my config before I removed neovim, can't promise that it still works, but maybe it will give you some hints: 

https://github.com/maximbaz/dotfiles/blob/2f1c6be73b66b41458cd802c9b125459c809c9fe/.config/nvim/init.vim
