### ISSUE TITLE
Display 'ok' component only conditionally, otherwise it's misleading in some cases

### ISSUE THREAD

**Issue by damnskippy** [maximbaz/lightline-ale#3]
Currently it appears the OK component seems to be displayed unconditionally, as a default status.
For instance, even in filetypes where ALE is not used (linter not available for the filetype), or not applicable (`.txt` file for instance).
I don't know if this is possible without underlying support from ALE, but it would be great if 'ok' component is displayed only when linting has actually successfully been done with zero warnings and errors?  And not displayed at all if linting is not ever attempted/done.  Or use a different indicator to say that linting is 'not applicable', for instance.
I just think that displaying 'ok' is a bit misleading in cases like these.

**Comment by maximbaz** [comment]
Thanks for creating the ticket!

To add some details, today we count number of errors/warnings and show OK if the number is `0`.

https://github.com/maximbaz/lightline-ale/blob/b8b201a7d00a9f1a5d96dd2c3451d64889161492/autoload/lightline/ale.vim#L20-L21

Instead, we shouldn't show OK in cases:

- if there was no linting performed at all
- if linting is currently in progress

I think there should be no indicator if linting has not been performed, the absence of "OK" or "checking" says it all 🙂

I'm not sure how to implement this, so help is definitely wanted.

**Comment by damnskippy** [comment]
In case you haven't seen this yet, I believe this should help: https://github.com/w0rp/ale/issues/1379

**Comment by damnskippy** [comment]
https://github.com/w0rp/ale/issues/1379 is now resolved, thanks to @w0rp.

**Comment by maximbaz** [comment]
Awesome, I pushed a commit that uses this new variable to hide "OK" if linting has never been performed. 

However it is still unknown to me how to hide components if linting is in progress, so let's keep the ticket open for now.

**Comment by w0rp** [comment]
`ale#engine#IsCheckingBuffer(buffer_number)` returns `1` if ALE is currently checking a buffer, and `0` if it isn't. You could use that.

**Comment by maximbaz** [comment]
Hm, thanks! I completely forgot that I actually already use this function in a different place 🤦‍♂️  

I believe now it works as expected. Thanks guys!
