### ISSUE TITLE
lightline-ale breaks goyo

### ISSUE THREAD

**Issue by sharktamer** [maximbaz/lightline-ale#5]
When using goyo, saving causes lightline to reappear. I've narrowed it down to lightline-ale by disabling other plugins.

**Comment by maximbaz** [comment]
lightline-ale is drawing indicators when ale is starting or finishing linting. If you don't want icons, I imagine you don't want linting to be performed at all, in which case consider disabling ALE by setting `let g:ale_enabled=0` - not only will you solve this issue, but you will also conserve some CPU cycles.

**Comment by maximbaz** [comment]
Closing, let me know if you still have questions.
