### ISSUE TITLE
FEATURE REQUEST: Hide "OK" text when ale is toggled off

### ISSUE THREAD

**Issue by prurigro** [maximbaz/lightline-ale#6]
Currently toggling ale off leaves `OK` in lightline. Ideally there'd be a fifth attribute that appeared to signify that ale isn't running.

**Comment by maximbaz** [comment]
That's a perfect idea, I'm only not sure about a yet another icon - the absence of `OK` should signify that ALE didn't run.

**Comment by maximbaz** [comment]
Done, no icons will be shown if ALE is disabled.

**Comment by prurigro** [comment]
Fantastic, thank you!
