### ISSUE TITLE
Unknown function: lightline#update

### ISSUE THREAD

**Issue by arnsa** [maximbaz/lightline-ale#7]
Hello,

I've installed lightline-ale package with Plug and when I launch vim or ALE linter runs, I keep on getting this error (it shows up and disappears after 1-2 seconds):

Error detected while processing User Auto commands for "ALELint":
E117: unknown function: lightline#update
Error detected while processing function <SNR>98_VimCloseCallback:
line 11:
E171: missing endif:

Any ideas on how to fix it? Thanks!

**Comment by maximbaz** [comment]
Hi, `lightline#update` is the main function of [lightline.vim](https://github.com/itchyny/lightline.vim) plugin, do you actually have it installed? 🙂 

This plugin is just a connector between ALE and lightline.vim, you have to install both.

**Comment by arnsa** [comment]
@maximbaz oh, haven't even thought about installing lightline plugin! Newbie here... Thank you for such a quick response, that fixed the problem!

**Comment by maximbaz** [comment]
Nothing to worry, I added this information to the README so that others are not confused with the same problem 👍
